unittests:
  stage: test
  image: python:3.4.5
  script:
    - cd web
    - pip install -q -r requirements.txt
    - python -c "import sys; print('\n'.join(sys.path))"
    - python -c "import sys; import os; sys.path.append(os.path.abspath(os.curdir))"
    - python -c "import sys; print('\n'.join(sys.path))"
    - nose2 -v project.tests.test_recipes_api
    - coverage run project/tests/test_recipes_api.py
  tags:
    - docker
